export default {
    ADDRESS_CONFIRMATION: "AddressConfirmation",
    ADDRESS_DETAILS_CONFIRMATION: "AddressDetailsConfirmation",
    AUTH: "Auth",
    BUTTONS: "Buttons",
    CARDS: "Cards",
    CARTICON: "CartIcon",
    CHECKBOXES: "Checkboxes",
    COMPONENTS: "Components",
    DEVHOME: "DevHome",
    EXPAND: "Expand",
    HOME: "Home",
    ICONS: "Icons",
    INPUTS: "Inputs",
    LOADING: "Loading",
    MODALS: "Modals",
    NOTIFICATIONS: "Notifications",
    SCREENS: "Screens",
    SEARCH_ADDRESS: "SearchAddress",
    SELECT: "Select",
    TYPOGRAPHY: "Typography",
}