export default {
    AUTH: "Auth",
    BUTTONS: "Buttons",
    CARDS: "Cards",
    CARTICON: "CartIcon",
    CHECKBOXES: "Checkboxes",
    COMPONENTS: "Components",
    DEVHOME: "DevHome",
    EXPAND: "Expand",
    HOME: "Home",
    ICONS: "Icons",
    INPUTS: "Inputs",
    LOADING: "Loading",
    MODALS: "Modals",
    NOTIFICATIONS: "Notifications",
    SCREENS: "Screens",
    SELECT: "Select",
    TYPOGRAPHY: "Typography",
}