export default [
    "apple",
    "apple-pay",
    "arrow-path",
    "balanced-diet",
    "bell",
    "brazil-flag",
    "cart",
    "chevron-down",
    "chevron-up",
    "clock",
    "colombia-flag",
    "color-clock",
    "cooking",
    "coupon",
    "delivery",
    "diet",
    "empty-cart",
    "error",
    "eye",
    "facebook",
    "google",
    "healthy",//Pending
    "instagra-oultined",//Pending
    "instagram",//Pending
    "map",//Pending
    "order",//Pending
    "payment-method",//Pending
    "piggy-bank",//Pending
    "pin",//Pending
    "plus",
    "question-mark-circle",
    "restaurant-house",//Pending
    "restaurant",//Pending
    "salad",//Pending
    "smartphone",//Pending
    "star-outlined",
    "star-solid",
    "success",//Pending
    "tips",//Pending
    "trash",
    "twitter",//Pending
    "united-states-flag",//Pending
    "warning",//Pending 
    "whatsapp",//Pending
    "x-mark",
]
